---
- name: setup openstack instance
  hosts: localhost
  user: stack
  sudo: True
  tasks:

  - name: download linux image
    get_url: url=http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img dest=./image.img

- name:
  hosts: localhost
  tasks:
  - name: create image
    command: openstack image create --disk-format qcow2 --container-format bare --public --file image.img linux-image

  - name: key
    command: openstack keypair create sshKey

  - name: launch an instance
    os_server:
        state: present
        name: linux-instance
        image: linux-image
        key_name: sshKey
        timeout: 200
        flavor: m1.small
        auto_floating_ip: yes
        security_groups: default

