- name: launch a compute instance
  hosts: localhost
  tasks:
    - name: launch an instance
      os_server:
        state: present
        name: vmteste
        image: cirros-0.3.5-x86_64-disk
        key_name: sshKey
        timeout: 200
        flavor: m1.tiny
        auto_floating_ip: yes
